### ISSUE TITLE
認識結果をTextで出力させたい

### ISSUE THREAD

**Issue by okulab-suzuki** [yoshito-n-students/label_detection_example#4]
岡田先生

不躾な質問で申し訳ありませんが、
私は認識したHAZMATの種類を判別することがやりたくてこのパッケージで認識した画像データの情報をテキストで表示（出力）させたいのですが、やり方がわかりません。（ターゲットファイルの名前を利用しようと思ったのですが上手くいきませんでした）
お力添え願えませんか？

**Comment by yoshito-okada** [comment]
質問の意味がよくわかっていないのですが，"How to detect your own targets" の 5 を実行した際に，検出したラベルの名前を表示したいということでしょうか？
であれば下記のfor文の中で names[i] を表示すればよいと思います．
https://github.com/yoshito-n-students/label_detection/blob/444f6e2a48311db269a217d1a81b7fbdc3dad9e3/src/test_label_detector.cpp#L49

**Comment by yoshito-okada** [comment]
質問者から長期間反応がないのでcloseします
